services:
  - type: web
    name: agro-ai-backend
    runtime: python
    rootDir: backend
    buildCommand: pip install -r ../requirements.txt && python manage.py collectstatic --noinput
    startCommand: python manage.py migrate && gunicorn backend.wsgi:application --bind 0.0.0.0:$PORT --workers 2 --timeout 120
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.6
      - key: DJANGO_SETTINGS_MODULE
        value: backend.settings
      - key: DJANGO_DEBUG
        value: "false"
      - key: DJANGO_ALLOWED_HOSTS
        value: agro-ai-12.onrender.com
      - key: MONGO_URI
        sync: false
      - key: MONGO_DB_NAME
        value: Agrodb
      - key: MONGO_SERVER_SELECTION_TIMEOUT_MS
        value: "3000"
      - key: MONGO_CONNECT_TIMEOUT_MS
        value: "3000"
      - key: MONGO_SOCKET_TIMEOUT_MS
        value: "3000"
      - key: MONGO_RUN_STARTUP_PING
        value: "true"
